<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/16
 * Time: 15:21
 */

namespace Admin\Controller;
use Think\Controller;
class ClientController extends CommonController
{
  function  index()
  {
      return parent::index(); // TODO: Change the autogenerated stub
  }
    function edit()
    {
        $data=array();
        $data['cilient_name']=$_POST['client_name'];

        $data['id']=$_POST['id'];
        $res=M('Client')->where('order_id='.$order_id)->save($data);
        if($res){
            $this->display();

        }else{
            return $this->error("更新失败");

        }

        parent::edit(); // TODO: Change the autogenerated stub
    }
    function add(){
        $data[]=$_POST;
        //var_dump($data);
        $res=M('client')->add($data);

    }
}